xl : 200 # 水路長(m)
nx: 51  # x方向格子数
j_channel: 2 # 水路の状態　1=一定勾配 2=勾配変化点あり
# j_channel=1の場合
slope: 0.002 # 全体の勾配
# j_channel=2の場合
x_slope : 130 # 勾配変化点
slope1 : 0.001 # 上流側勾配
slope2 : 0.01 # 下流側勾配
xb1 : 4 # 突起始り格子番号
xb2 : 5 # 突起頂点番号
xb3 : 6 # 突起終了番号
dbed : 0.00 #突起高さ(m)
qp : 1 #単位幅流量(m**2/2)
g : 9.8 #重力加速度
snm : 0.025 # 粗度係数
alh : 0.6 # 水位計算緩和係数
lmax : 50 # 水位計算最大繰り返し回数
errmax : 0.0001 # 打ち切り誤差
hmin : 0.01 # 最小水深(m)
j_upstm : 2 # 上流端の条件 1=Wall, 2=Free, 3=Fixed Value
j_dwstm : 3 # 下流端の条件
alpha_up: 1.0 # 上流端の水深(等流水深に対する割合)
alpha_dw: 1.0 # 下流端の水深(等流水深に対する割合)

etime : 400 # 計算終了時間(sec)
dt : 0.05 # 計算タイムステップ
tuk : 10 # アウトプットインターバル
